@startuml Diagrama de Despliegue

node userPC <<device>>{
    node sistemaOperativo <<execution enviroment>>{
        node navegador <<execution enviroment>>{
        }
    }
}

node servidor <<device>>{
    node ubuntu <<execution enviroment>>{
        node mysql <<execution enviroment>>{
            artifact testInsight <<artefact>>
        }
        node nodeJS <<execution enviroment>>{
            artifact app.js <<artefact>>
        }
        node CADDY <<execution enviroment>>{
            artifact CADDYFILE <<artefact>>
        }
        mysql -- nodeJS: tcp/ip
        nodeJS -- CADDY: https
    }
}

navegador -- CADDY : https

node googleServicePC <<device>>{
    node sistemaOperativoGoogleService <<execution enviroment>>{
        node googleapis <<execution enviroment>>{

        }
    }
}

googleapis -- nodeJS : https


node emailServicePC <<device>>{
    node sistemaOperativoEmailService <<execution enviroment>>{
        node mailersend <<execution enviroment>>{

        }
    }
}

mailersend -- nodeJS : https

@enduml
