@startuml Diagrama de Despliegue

node userPC <<device>>{
    node sistemaOperativo <<execution enviroment>>{
        node navegador <<execution enviroment>>
    }
}

node servidor <<device>>{
    node ubuntu <<execution enviroment>>{
        rectangle mysql <<execution enviroment>>{
            artifact testInsight <<artefact>>
        }
        rectangle nodeJS <<execution enviroment>>{
            artifact app.js <<artefact>>
        }
        rectangle PM2 <<execution enviroment>>
        rectangle CADDY <<execution enviroment>>
        mysql -- nodeJS: label
        nodeJS -- PM2: label
        nodeJS -- CADDY: label
    }
}

userPC -- servidor : https

@enduml
