@startuml Diagrama de Despliegue

node userPC <<device>>{
    node sistemaOperativo <<execution enviroment>>{
        node navegador <<execution enviroment>>{
        }
    }
}

node servidor <<device>>{
    node ubuntu <<execution enviroment>>{
        node mysql <<execution enviroment>>{
            
        }
        node nodeJS <<execution enviroment>>{
        }
        node CADDY <<execution enviroment>>{

        }
        mysql -- nodeJS: <<tcp/ip>>
        nodeJS -- CADDY: <<https>>
    }
}

artifact testInsight <<artefact>>
mysql -[dashed]-> testInsight : [dashed]

artifact app.js <<artefact>>
nodeJS -[dashed]-> app.js : [dashed]

artifact CaddyFile <<artefact>>
CADDY -[dashed]-> CaddyFile : [dashed]


navegador -- CADDY : <<https>>

node googleServicePC <<device>>{
    node sistemaOperativoGoogleService <<execution enviroment>>{
        node googleapis <<execution enviroment>>{

        }
    }
}

googleapis -- nodeJS : https


node emailServicePC <<device>>{
    node sistemaOperativoEmailService <<execution enviroment>>{
        node mailersend <<execution enviroment>>{

        }
    }
}

mailersend -- nodeJS : https

@enduml
